# Generated by Django 5.2.4 on 2025-07-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiliVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bvid",
                    models.CharField(max_length=20, unique=True, verbose_name="BV号"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("cover", models.URLField(verbose_name="封面URL")),
                ("author", models.CharField(max_length=100, verbose_name="UP主")),
                ("pub_date", models.DateField(verbose_name="发布日期")),
                ("play_count", models.IntegerField(default=0, verbose_name="播放量")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("description", models.TextField(blank=True, verbose_name="视频简介")),
            ],
            options={
                "verbose_name": "B站视频",
                "verbose_name_plural": "B站视频",
            },
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilistudy.bilivideo",
                        verbose_name="视频",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户课程",
                "verbose_name_plural": "用户课程",
                "unique_together": {("user", "video")},
            },
        ),
        migrations.CreateModel(
            name="VideoEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=20, verbose_name="分集ID")),
                ("title", models.CharField(max_length=200, verbose_name="分集标题")),
                ("duration", models.IntegerField(default=0, verbose_name="时长(秒)")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="bilistudy.bilivideo",
                        verbose_name="所属视频",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频分集",
                "verbose_name_plural": "视频分集",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "last_position",
                    models.IntegerField(default=0, verbose_name="上次观看位置(秒)"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="bilistudy.usercourse",
                        verbose_name="用户课程",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilistudy.videoepisode",
                        verbose_name="视频分集",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习进度",
                "verbose_name_plural": "学习进度",
                "unique_together": {("user_course", "episode")},
            },
        ),
    ]
