# Generated by Django 5.2.4 on 2025-07-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercourse",
            options={"verbose_name": "课程", "verbose_name_plural": "课程"},
        ),
        migrations.AlterUniqueTogether(
            name="usercourse",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="learningprogress",
            name="user_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="bilistudy.usercourse",
                verbose_name="课程",
            ),
        ),
        migrations.RemoveField(
            model_name="usercourse",
            name="user",
        ),
    ]
