# Generated by Django 5.2.4 on 2025-07-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0002_remove_user_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercourse",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bilistudy.bilivideo",
                unique=True,
                verbose_name="视频",
            ),
        ),
    ]
