# Generated by Django 5.2.4 on 2025-07-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0003_add_unique_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="custom_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="自定义课程名称"
            ),
        ),
    ]
