# Generated by Django 5.2.4 on 2025-07-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0004_usercourse_custom_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_days", models.IntegerField(verbose_name="计划学习总天数")),
                (
                    "daily_minutes",
                    models.IntegerField(verbose_name="每天学习时间（分钟）"),
                ),
                (
                    "focus_modules",
                    models.TextField(blank=True, verbose_name="重点学习模块"),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="开始日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user_course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plan",
                        to="bilistudy.usercourse",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
            },
        ),
        migrations.CreateModel(
            name="DailyStudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_date", models.DateField(verbose_name="学习日期")),
                (
                    "study_minutes",
                    models.IntegerField(default=0, verbose_name="实际学习时间（分钟）"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="学习备忘/记录")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_episodes",
                    models.ManyToManyField(
                        blank=True,
                        to="bilistudy.videoepisode",
                        verbose_name="完成的分集",
                    ),
                ),
                (
                    "study_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="bilistudy.studyplan",
                        verbose_name="学习计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日学习记录",
                "verbose_name_plural": "每日学习记录",
                "ordering": ["-study_date"],
                "unique_together": {("study_plan", "study_date")},
            },
        ),
    ]
