# Generated by Django 5.2.4 on 2025-07-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0005_studyplan_dailystudyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercourse",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="bilistudy.bilivideo",
                verbose_name="视频",
            ),
        ),
    ]
