# Generated by Django 5.2.4 on 2025-07-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0007_emailverification_studyplan_user_usercourse_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.CreateModel(
            name="EpisodeCompletionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_date", models.DateField(verbose_name="完成日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilistudy.videoepisode",
                        verbose_name="分集",
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilistudy.usercourse",
                        verbose_name="用户课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "分集完成记录",
                "verbose_name_plural": "分集完成记录",
                "ordering": ["-completed_date", "episode__order"],
                "unique_together": {("user_course", "episode")},
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
