# Generated by Django 5.2.4 on 2025-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0008_learningprogress_completed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailystudyrecord",
            name="completed_episodes",
        ),
        migrations.RemoveField(
            model_name="learningprogress",
            name="last_position",
        ),
        migrations.DeleteModel(
            name="EpisodeCompletionRecord",
        ),
    ]
