# Generated by Django 5.2.4 on 2025-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0009_remove_dailystudyrecord_completed_episodes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="会话ID")),
                ("user_message", models.TextField(verbose_name="用户消息")),
                ("ai_response", models.TextField(verbose_name="AI回复")),
                (
                    "chat_type",
                    models.CharField(
                        default="general", max_length=50, verbose_name="聊天类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "聊天历史",
                "verbose_name_plural": "聊天历史",
                "ordering": ["-created_at"],
            },
        ),
    ]
