# Generated by Django 5.2.4 on 2025-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0011_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="enable_content_filter_reminder",
            field=models.BooleanField(default=True, verbose_name="启用学习内容提醒"),
        ),
    ]
