# Generated by Django 5.2.4 on 2025-07-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0012_userpreference_enable_content_filter_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "白天模式"), ("dark", "夜间模式")],
                default="light",
                max_length=10,
                verbose_name="主题偏好",
            ),
        ),
    ]
