# Generated by Django 5.2.4 on 2025-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilistudy", "0013_userpreference_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="has_viewed_guide",
            field=models.BooleanField(default=False, verbose_name="已查看新手指南"),
        ),
    ]
